---
- name: Create etcd user
  user:
    name: etcd
    group: root
    uid: 1000
    
- name: Download the etc tar file 
  get_url:
    url: "{{ DOWNLOAD_URL }}/{{ ETCD_VER }}/etcd-{{ ETCD_VER }}-linux-amd64.tar.gz"
    dest: "/etcd-{{ ETCD_VER }}-linux-amd64.tar.gz"
    owner: root
    group: root 
    mode: 0666

- name: Create /etcd dir
  file:
    path: /etcd
    state: directory
    owner: etcd 
    group: root 
    mode: 0775

- name: Create data dir
  file:
    path: /data
    state: directory
    owner: etcd
    group: root
    mode: 0777

- name: Unpack the tar file
  command: "tar xzvf /etcd-{{ ETCD_VER }}-linux-amd64.tar.gz -C /etcd --strip-components=1"

- name: Remove the tar file
  file:
    path: "/etcd-{{ ETCD_VER }}-linux-amd64.tar.gz"
    state: absent

